### ISSUE TITLE
prepareMessage is not function

### ISSUE THREAD

**Issue by azudindaem** [RynKings/whatsapp-hook-md#1]
Salam mas,  prepareMessage masih lib yang lama? 

https://github.com/RynKings/whatsapp-hook-md/blob/b25b00dba633152fb21ab741b0db607d0302542f/lib/client.js#L126

**Comment by RynKings** [comment]
> Salam mas, prepareMessage masih lib yang lama?
> 
> https://github.com/RynKings/whatsapp-hook-md/blob/b25b00dba633152fb21ab741b0db607d0302542f/lib/client.js#L126

Loh iyya mas lupa rename sorry" ganti jadi serializeMessage mas

**Comment by RynKings** [comment]
> Salam mas, prepareMessage masih lib yang lama?
> 
> https://github.com/RynKings/whatsapp-hook-md/blob/b25b00dba633152fb21ab741b0db607d0302542f/lib/client.js#L126

c nya coba di hilangin mas saya lupa kemarin

**Comment by azudindaem** [comment]
iyah makasih
